feat: LightGBM 구현 #43
boostcampaitech6/level1-bookratingprediction-recsys-02 pull request #74
Opened 2023-12-29 00:55 UTC by jinmin111

## Overview
- LightGBM 모델을 구현했습니다.

## Change Log
-

## To Reviewer
-

## Issue Tags
- Closed #43 
- See also: #

2024-01-01 06:58 UTC, GangBean requested changes
trainer.py 에 남긴 코멘트와 관련해, 타 모델에 영향이 가지 않을지 확인 부탁드립니다!

2024-01-01 06:58 UTC, GangBean commented on main.py
👍 프로젝트 종료 이후에도 시도해보고 싶었던 걸 끝까지 마무리하는 모습이 보기 좋습니다!

2024-01-01 06:58 UTC, GangBean commented on src/ml_config/LightGBM.py
👍 Config 모듈로 모델의 하이퍼파라미터를 관리하는 게 arg기반 방법에 비해, 실행과 코드와의 버전 일관성 측면에서 좋아보여 관리측면에서 더 유용할 것 같습니다! 좋은 방법이라 생각합니다.

2024-01-01 06:58 UTC, GangBean commented on src/models/GBDT/LightGBM_model.py
👍 LGBModel을 바로 사용하지 않고, 한번 wrapping한 클래스로 구현함으로써 해당 프로젝트 내에서 기능을 확장하기 유리할 것 같습니다! 클래스 Naming도 축약형이 아닌 LightGBM으로 풀어써주신 부분이 이해하기 더 용이해 좋아 보입니다.

2024-01-01 06:58 UTC, GangBean commented on src/models/__init__.py
LGTM 💯

2024-01-01 06:58 UTC, GangBean commented on src/train/trainer.py
> +        # 'verbose': True,
@jinmin111 🤔 ml_train을 사용하는 다른 모델에서 'verbose' parameter를 사용하진 않나요? 다른 모델의 학습에 영향이 가진 않을까 우려됩니다! 아래처럼 lightgbm 모델일 경우에만 별도 처리를 해주는 방법은 어떨까요??
``` python
configs = {
        'eval_set': [(data['X_train'], data['y_train']), (data['X_valid'], data['y_valid'])],
        'verbose': True,
}

if args.model == 'LigthGBMModel':
    configs.pop('verbose')
```

2024-01-01 06:58 UTC, GangBean commented on src/utils.py
> +from src.ml_config.LightGBM import LightGBMConfig
👍 from import 로 사용하려는 모듈내에서 필요한 객체만 import 해온 부분이 굉장히 좋아보입니다! 메모리 효율측면에서도 좋고, 가독성도 좋고, 해당 모듈의 의존성 관리 측면에서도 좋아보입니다.
🤔 한가지 고민해볼 수 있을 만한 점으론, 절대경로와 상대경로의 장단점을 비교해볼 수 있을 것 같습니다. 참고만 해주세요!
https://wikidocs.net/153154

2024-01-01 07:17 UTC, ChangZero commented
PR 컨벤션 확인 부탁드려요!!

2024-01-02 12:18 UTC, jinmin111 commented on src/train/trainer.py
> +        # 'verbose': True,
verbose 파라미터는 모델 train logging 출력 여부여서 모델 자체에는 영향이 없긴 합니다. 로깅해주는게 더 나을 것 같아서 따로 처리해주도록 하겠습니다.

2024-01-02 12:31 UTC, jinmin111 commented
> PR 컨벤션 확인 부탁드려요!!

2024-01-03 12:42 UTC, GangBean approved these changes
👍 빠른 피드백 감사드립니다! 💯

2024-01-03 12:42 UTC, merged